# Generated by Django 5.2.9 on 2025-12-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_medicine_category_medicine_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='image',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
