# Generated by Django 5.2.9 on 2025-12-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_admin_shippingaddress_medicine_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
